name: .NET CI/CD

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    - name: Restore dependencies
      run: dotnet restore ClinicManager.sln

    - name: Build
      run: dotnet build ClinicManager.sln --configuration Release --no-restore

    - name: Test
      run: dotnet test ClinicManager.sln --configuration Release --no-build --verbosity normal
